### ISSUE TITLE
Springboot 3.3 Stream closed

### ISSUE THREAD

**Issue by marcantoine-bibeau** [jesperfj/force-rest-api#104]
I don't know the cause but as soon as I update our project to use Springboot 3.3.0, we start getting this exception. 

Any clue on your side? 

java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:169)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:345)
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
	at com.force.api.http.Http.readResponse(Http.java:57)
	at com.force.api.http.Http.send(Http.java:113)
	... 17 common frames omitted
Wrapped by: java.lang.RuntimeException: java.io.IOException: Stream closed
	at com.force.api.http.Http.send(Http.java:118)
	at com.force.api.ForceApi.apiRequest(ForceApi.java:499)
	at com.force.api.ForceApi.queryAny(ForceApi.java:343)
	at com.force.api.ForceApi.query(ForceApi.java:315)

**Comment by jesperfj** [comment]
Sorry I don't know what could cause it. I have not used Springboot in a long time.
