### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by montague** [jesperfj/force-rest-api#53]
Pulled down the project to start working on adding a timeout to HTTP requests, got this failure when trying to compile `master` by running `mvn install -X -DskipTests`:
```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project force-rest-api: Compilation failure: Compilation failure: 
[ERROR] /dev_exclusions/force-rest-api/src/main/java/com/force/api/ForceApi.java:[330,81] error: method traverse in interface TreeNode cannot be applied to given types;
[ERROR]  actual and formal argument lists differ in length
[ERROR] /dev_exclusions/force-rest-api/src/main/java/com/force/api/ForceApi.java:[387,109] error: method traverse in interface TreeNode cannot be applied to given types;
[ERROR]  actual and formal argument lists differ in length
[ERROR] /dev_exclusions/force-rest-api/src/main/java/com/force/api/ForceApi.java:[391,57] error: method traverse in interface TreeNode cannot be applied to given types;
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project force-rest-api: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:656)
	at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more```

**Comment by jesperfj** [comment]
hm weird. Not on computer right now but will try to repro asap.

**Comment by montague** [comment]
thanks @jesperfj, i appreciate it.

**Comment by jesperfj** [comment]
This could be related to the change in version range that I just did for
jackson. I didn't test all possible versions. I haven't had a lot of
compatibility issues with jackson so I took the chance and opened up the
range.

**Comment by montague** [comment]
sounds like a good bet. `force-rest-api-0.0.37` builds successfully for me.

**Comment by jesperfj** [comment]
Which version of jackson-bind was used in your compilation?

**Comment by jesperfj** [comment]
I just tried building it using Heroku's default Java buildpack and I didn't get any errors. It's a simple way to do a clean build outside of your own environment. Assuming you have a Heroku account, you just do:

```
heroku create
git push heroku master
```

**Comment by montague** [comment]
`jackson-databind:3.0.0-SNAPSHOT` is what maven pulled down for us.

Here's a screenshot of the error in intellij.
<img width="884" alt="screen shot 2017-10-12 at 9 06 48 am" src="https://user-images.githubusercontent.com/297091/31497336-d1460532-af2c-11e7-8567-b1bade17fded.png">


i understand if you don't have time to help debug this. unfortunately, if i can't get past this issue, we'll have to pull the project from our codebase or fork it. i'd love to avoid that if possible.

is there any significance to the fact that the previous `0.0.37` release builds ok for me? doesn't the dependency below indicate that we want anything below `3.0`? yet we're getting `3.0.0-SNAPSHOT`.
```
<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>[2.5,3.0)</version>
        </dependency>
```

**Comment by jesperfj** [comment]
Weird. You should be using 2.9.1 or older. It should never be pulling
SNAPSHOTs.

**Comment by jesperfj** [comment]
Can you manually change 3.0 to 2.9 in the version range and try again?

**Comment by montague** [comment]
``` <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>[2.5,2.9)</version>
        </dependency>
```
this worked

**Comment by jesperfj** [comment]
Great.

I think it needs to be a right bracket, not right parenthesis in order to include 2.9.x versions. I am going to do a 0.0.39 release with that change just to keep it separated from your PR. Stay tuned.

**Comment by jesperfj** [comment]
3e38454983bca847aad9e5d051ea0f314bc7aee0 should fix this issue. Please verify by pulling and compiling from master.

**Comment by montague** [comment]
verified. compilation successful :)
